language: "python"

sudo: required
dist: xenial

python:
  - "3.7"

before_install:
  - "pip install --no-cache-dir poetry"

install:
  - "poetry install"

script:
  - "poetry run flake8 --max-line-length=120 ."

notifications:
  email:
    on_success: "never"
    on_failure: "always"
